##################################################################
CROSS_COMPILE ?= aarch64-none-elf-
#
# PWD stays at example/kria-k26 when using make -C subdirs
KERNEL_DIR ?= $(PWD)/../..
KERNEL_DEV := cortex-a53

CFLAGS += -I. -I../include
FLAGS += -I. -I../include

include $(KERNEL_DIR)/config/$(KERNEL_DEV)/Makefile.dev

# Larger map / keep frame pointers optional
CFLAGS += -fno-omit-frame-pointer
