##################################################################
CROSS_COMPILE=arm-none-eabi-
#
KERNEL_DIR ?= $(PWD)/../..
KERNEL_DEV := cortex-m3

#
# C flags
CFLAGS += -DSTM32L100xB -DUSE_FULL_LL_DRIVER
CFLAGS +=  -I. -I../include
# ASM flags
FLAGS += -I. -I../include
#
include $(KERNEL_DIR)/config/$(KERNEL_DEV)/Makefile.dev

