##################################################################
# Prefer Vitis baremetal toolchain; override with CROSS_COMPILE=
CROSS_COMPILE ?= /opt/xilinx/Vitis/2023.2/gnu/aarch64/lin/aarch64-none/bin/aarch64-none-elf-
#
# PWD stays at example/qemu-a53 when using make -C subdirs
KERNEL_DIR ?= $(PWD)/../..
KERNEL_DEV := cortex-a53

CFLAGS += -I. -I../include
FLAGS += -I. -I../include

include $(KERNEL_DIR)/config/$(KERNEL_DEV)/Makefile.dev

# Larger map / keep frame pointers optional
CFLAGS += -fno-omit-frame-pointer
