################################################################################
include ../Makefile.rules
#
vpath %.c src
vpath %.S src
vpath %.h src ../include
vpath %.h54 src ../include
#
SRCS = \
       stacks.c \
       main.c

#
sub:  $(LISTDIR)  $(OBJS)

include Makefile.dep


