include ../Makefile.rules
#
vpath %.c $(KERNEL_DIR)/kernel $(KERNEL_DIR)/config/$(KERNEL_DEV)
vpath %.asm $(KERNEL_DIR)/config/$(KERNEL_DEV)
#
SRCS = cpu_support.asm cpu_support.c ittrium.c
#
sub: $(LISTDIR) $(OBJS)
