################################################################################
include ../Makefile.rules
#
vpath %.c src
vpath %.S src
vpath %.h src ../include
vpath %.h55 src ../include
#
SRCS = \
       test.c

#
sub:  $(LISTDIR)  $(OBJS)

include Makefile.dep


