##################################################################
CROSS_COMPILE ?= arm-none-eabi-
#
EXAMPLE_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
KERNEL_DIR ?= $(abspath $(EXAMPLE_DIR)/../..)
KERNEL_DEV := cortex-m3

# https://github.com/ARM-software/CMSIS_5 — Core only (no Device/HAL)
CMSIS_ARM_PATH ?= $(KERNEL_DIR)/third_party/CMSIS_5

ifeq ($(wildcard $(CMSIS_ARM_PATH)/CMSIS/Core/Include/core_cm3.h),)
$(error CMSIS Core not found at $(CMSIS_ARM_PATH). Clone: git clone --depth 1 -b 5.9.0 https://github.com/ARM-software/CMSIS_5.git $(CMSIS_ARM_PATH))
endif

CFLAGS += -I. -I../include
FLAGS += -I. -I../include
FLAGS += -I$(KERNEL_DIR)/config/$(KERNEL_DEV)

include $(KERNEL_DIR)/config/$(KERNEL_DEV)/Makefile.dev
