#
# Cortex-m3 makefile
#
ASM = $(CROSS_COMPILE)as
CC = $(CROSS_COMPILE)gcc
RM = rm -rf
LNK = $(CROSS_COMPILE)gcc
AR = $(CROSS_COMPILE)ar
SIZE = $(CROSS_COMPILE)size
CP = cp -f
MV = mv -p
CAT = cat
DD = dd
MKDIR = mkdir -p
#
KERNEL_DEV = cortex-m3
#
OBJDIR = obj
LISTDIR = list
#
CMSIS = $(CMSIS_ARM_PATH)
CMSIS_DEV = $(CMSIS_DEV_PATH)
HAL = $(HAL_PATH)

ifeq ($(DEBUG), 1)
	CFLAGS_OPT := -g -Og
else
	CFLAGS_OPT := -Os
endif

#
FLAGS_COMMON := \
	       -mcpu=cortex-m3 -mthumb \
	       -mfloat-abi=soft \
	       -I$(KERNEL_DIR)/include \
	       -I$(KERNEL_DIR)/config/$(KERNEL_DEV) \

# CMSIS Core required; device/HAL optional (board trees)
ifneq ($(CMSIS),)
CFLAGS += -I$(CMSIS)/CMSIS -I$(CMSIS)/CMSIS/Core/Include
endif
ifneq ($(CMSIS_DEV),)
CFLAGS += -I$(CMSIS_DEV)/Include
vpath %.s $(CMSIS_DEV)/Source/Templates/gcc
vpath %.c $(CMSIS_DEV)/Source/Templates
endif
ifneq ($(HAL),)
CFLAGS += -I$(HAL)/Inc
vpath %.c $(HAL)/Src
endif

CFLAGS += $(FLAGS_COMMON) $(CFLAGS_OPT)
CFLAGS += --specs=nano.specs
CFLAGS += -fdata-sections -Wall -fstack-usage -MMD -MP
# ASM flags
FLAGS += $(FLAGS_COMMON)
#
LDFLAGS += --specs=nosys.specs
LDFLAGS += -Wl,-Map="$(TARGET).map" -Wl,--gc-sections -static
LDFLAGS += --specs=nano.specs
LDFLAGS += $(FLAGS_COMMON)
LDFLAGS += -Wl,--start-group -lc -lm -Wl,--end-group
#
OBJS = $(patsubst %.c,%.o,$(filter %.c,$(SRCS)))
OBJS += $(patsubst %.s,%_.o,$(filter %.s,$(SRCS)))
LIST = $(patsubst %.c,%.lst,$(filter %.c,$(SRCS)))
vpath %.o $(OBJDIR)
vpath %.lst $(LISTDIR)

all: sub

$(OBJDIR):
	$(MKDIR) $(OBJDIR)

$(LISTDIR):
	$(MKDIR) $(LISTDIR)

%_.o: %.s
	$(ASM) $(FLAGS) $< -o ../$(OBJDIR)/$@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o ../$(OBJDIR)/$(notdir $@)

clean:
	$(RM) $(OBJDIR) $(LISTDIR) $(TARGET)

.PHONY: all clean sub
